version: 0.1.0.{build}

skip_branch_with_pr: false
skip_commits:
  message: /!nobuild/
skip_tags: false

environment:
  fast_finish: true

init:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds.
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  
install:
  - cmd: choco install 7zip.commandline
  

cache:
  - C:\ProgramData\chocolatey\lib
  - C:\ProgramData\chocolatey\bin

build_script:
  - cmd: for /f "delims=" %%i in ('git describe --tags') do set TRM_VERSION=%%i
  - cmd: appveyor UpdateBuild -Version "%TRM_VERSION%.%APPVEYOR_BUILD_NUMBER%"
  - cmd: 7za a -bb0 dummy.miz D:\DCS_Missions\TRM\* -xr!.git -x!*.miz -x!*.yml
  - cmd: IF /I "%APPVEYOR_REPO_TAG%"=="true" (ren dummy.miz TRM_%APPVEYOR_REPO_TAG_NAME%.miz) ELSE (ren dummy.miz TRM_%APPVEYOR_BUILD_VERSION%.miz)

test: off

artifacts:
  - path: '*.miz'
    name: TRM
  
deploy:
  - provider: GitHub
    auth_token:
      secure: oqhY5z4JkQh4bNg2w52lZ5+XL6WOoJxwkfhXBUdwvThrqT+4rX5QsN7DmP9MuRTa
    artifact: 'TRM'
    draft: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
